### ISSUE TITLE
Plotting error in plot_sensitivities()

### ISSUE THREAD

**Issue by ArnoVand** [scottshambaugh/monaco#11]
When I try plotting the sensitivities after a run, it throws an error 'fig.set_layout_engine('tight') does not exist. I do **not** have the same problem with e.g. plot_cov_corr().

**Comment by scottshambaugh** [comment]
Hi @ArnoVand, what version of matplotlib do you have installed? That code path is working fine for me here (and is exercised during the automated test suite). It looks like this feature was introduced in matplotlib 3.6, which is the minimum version that monaco requires: https://matplotlib.org/3.6.3/api/figure_api.html#matplotlib.figure.Figure.set_layout_engine

**Comment by scottshambaugh** [comment]
I'll close the issue for now, but if you see that your matplotlib version is high enough then please leave a comment and I'll take another look!
