### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'singlethreaded'

### ISSUE THREAD

**Issue by hafizhfp** [scottshambaugh/monaco#4]
Hello there,

I tried to run the simulator to check if this package is working or not, but I encountered an error like in the title when I tried to run the mc.Sim(...) in template file. When I omitted the singlethreaded argument, the error is gone and the program could run. I already checked init and mc_sim file, but I couldn't find anything wrong in there. I hope you can find and fix the problem. Thank you.

**Comment by scottshambaugh** [comment]
Hi @hafizhfp, thanks for reporting this issue. I can't reproduce it in a clean environment however. Could you please provide the following information to help debug this?

- Operating system
- Version of python
- Version of monaco installed
- Upload a copy of the template file which you are running

**Comment by hafizhfp** [comment]
Thank you for the reply, @scottshambaugh. This is the information that I can provide when that error happened:
Operating system: Windows 10 64-bit
Version of python: Python 3.7.16
Version of monaco installed: 0.4.0
The template file (should be the same from the github repository): 
[template_monte_carlo_sim_1.txt](https://github.com/scottshambaugh/monaco/files/10694868/template_monte_carlo_sim_1.txt)

Additional note: Actually, I tried to run that template file in Anaconda environment when I found the error. When I tried to make a new environment by installing VS Code, the singlethreaded argument was accepted and the template file could be run.
Another additional note: It seems like the pip installation only works with python 3.10 or below. The newest version of python is now 3.11 and that made the pip couldn't work. I already installed both version of the python and switched to the old one, but I suggest you can update the requirement to install the monaco if possible.

Thank you.

**Comment by scottshambaugh** [comment]
Thanks @hafizhfp, that helps. Right now the latest version of monaco only supports Python 3.8, 3.9, and 3.10. I will add 3.11 support as soon as possible, but that is waiting on the numba dependency to be updated (see this issue: https://github.com/numba/numba/issues/8304). However if you create an environment with one of the above Python versions, you should be able to update to the latest version of Monaco (0.9.0) and this error will be resolved. Let me know if you run into other issues!

**Comment by scottshambaugh** [comment]
Hi @hafizhfp, I've made the numba dependency optional which allowed me to add python 3.11 support in the latest monaco version just released today (0.9.1).
