### ISSUE TITLE
sim.plot doesn't use input variable list

### ISSUE THREAD

**Issue by bdickerson5** [scottshambaugh/monaco#6]
I'm trying to down-scope the total variables I plot in mc_sim.plot(), because I have a lot of inputs that make the plot un-usable.  When adding the value scalarvars to provide this list no change in output occurs.  Reading the source code it appears that scalarvars is not actually used.  There is an if statement that checks for if None, but the output of that function does not go into the multi_plot function.  In multi_plot call of mc_sim.plot it specifies x_vals are pulled from self.list and ignore any potential input from scalarvars.  

I would also recommend in fix that scalarvars be a two parts list [[plot_invars], [plot_outvars]].  THus allowing user to downselect either category independently.

**Comment by scottshambaugh** [comment]
Thank you for finding this bug! This has been fixed in version 0.10.0 which I just released, please let me know if you run into any other issues!
