### ISSUE TITLE
numpy.linalg.det FloatingPointError: underflow

### ISSUE THREAD

**Issue by MariovdBerg** [scottshambaugh/monaco#7]
I've encountered _underflow_ errors in `dvars.sensitivity.py`, line 273 (`np.linalg.det(R)`). This error is most likely more related to my model than the library, but switching to scipy.linalg.det(R) solved this in my case (25 inputvars, 1 main outputvar).

From [scipy.linalg.det](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html) documentation:
> Even the input array is single precision (float32 or complex64), the result will be returned in double precision (float64 or complex128) to prevent overflows.

Possible solution is to set these cells to 0 if encountered, but this may introduce singular matrices.

**Comment by scottshambaugh** [comment]
Interesting! I have this switched over to the scipy version of the determinant now in the latest release just published (`v0.11.6`). 

For what it's worth, I don't actually find DVARS *that* useful - it's fairly sensitive to the sample set (pretty big error bars on the output IMO) and doesn't scale its compute well. Take it with a grain of salt.

**Comment by MariovdBerg** [comment]
Although the sensitivity ranking (and to a large extend the sensitivity ratio as well) converges when the simulation was run more than 400 times (I ran 512 simulations due to Sobol random sampling), the compute time for calculating the sensitivity was roughly 60 minutes (25 input vars).

So, I do agree the compute time doesn't scale that well, but doing a sensitivity analysis on just a input and output dataset is very useful in itself considering the wide variety of models applicable.

Regardless, thanks for taking my suggestion into consideration!

**Comment by scottshambaugh** [comment]
Note that I reverted this fix in the releasing-now 0.12.1, as is was breaking numba compilation. Instead, the `R` matrix is explicitly cast as a np.float64 type (though that was the default so not sure if the before explanation was correct...). Please let me know if you see this issue again and I can try and reproduce.
